### ISSUE TITLE
TypeError: can't convert np.ndarray of type numpy.str_.

### ISSUE THREAD

**Issue by Diankuang-Wu** [montrealrobotics/active-domainrand#4]
Hello, when I run the code by the command: **pusher --experiment-name=unfreeze-policy --freeze-discriminator --experiment-prefix="true-baseline" --agent-name=baseline --initial-svpg-steps=1e6 --continuous-svpg --freeze-svpg --seed=123**, encounter the error as below:

Traceback (most recent call last):
  File "/home/wu/active-domainrand/experiments/domainrand/experiment_driver.py", line 82, in <module>
    svpg_timesteps, log_path=paths['policy_logs'], plot_path=paths['policy_plots'])
  File "/home/wu/active-domainrand/experiments/domainrand/common/utils/visualization.py", line 184, in plot_value
    _, value = simulator_agent.svpg.select_action(policy_idx, values)
  File "/home/wu/active-domainrand/experiments/domainrand/common/svpg/svpg.py", line 104, in select_action
    state = torch.from_numpy(state).float().unsqueeze(0).to(device)     
### TypeError: can't convert np.ndarray of type numpy.str_. The only supported types are: float64, float32, float16, int64, int32, int16, int8, uint8, and bool.

But, I run **lunar**, it's ok, no error. Could you please tell me how to handle with it? Thank you.

**Comment by jgkim2020** [comment]
@bhairavmehta95 I'm having the exact same issue as @Diankuang-Wu
FYI I'm using python 3.7 (conda env)

edit: might it be caused by some kind of empty string or NaN value? I'm clueless..

**Comment by bhairavmehta95** [comment]
This seems to have to do with a change in numpy version, and how they handle different types of arrays.

In the `visualization.py` script, you'll see something that says `[['default'] * something]` 

You can replace that with: https://github.com/montrealrobotics/active-domainrand/blob/a60a2678995178e5d2ea28218bf9b26c7450cd4a/common/envs/wrappers.py#L63

`env.dimensions[dimension].default_value for dimension in range(0, nparams)`

Unfortunately, my setup doesn't error here so I'm not super sure how to recreate

**Comment by jgkim2020** [comment]
> This seems to have to do with a change in numpy version, and how they handle different types of arrays.
> 
> In the `visualization.py` script, you'll see something that says `[['default'] * something]`
> 
> You can replace that with:
> 
> https://github.com/montrealrobotics/active-domainrand/blob/a60a2678995178e5d2ea28218bf9b26c7450cd4a/common/envs/wrappers.py#L63
> 
> `env.dimensions[dimension].default_value for dimension in range(0, nparams)`
> 
> Unfortunately, my setup doesn't error here so I'm not super sure how to recreate

What is the **env** in **env.dimensions[dimension].default_value for dimension in range(0, nparams)**? I assumed it was **self.randomized_env** judging by the Visualizer object implementation but it doesn't seem to be the **RandomizedEnvWrapper** in wrappers.py.

edit: Oh, and by the way, which version of numpy are you using? Thanks for the quick reply!
